# Generated by Django 5.0.6 on 2025-08-31 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0013_alter_division_options_alter_heatassignment_options_and_more'),
        ('registration', '0005_alter_team_options_alter_team_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.PositiveIntegerField()),
                ('time_seconds', models.PositiveIntegerField(blank=True, help_text='Tiempo total en segundos.', null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('penalties', models.IntegerField(default=0)),
                ('tiebreak_seconds', models.PositiveIntegerField(blank=True, help_text='Tie-break en segundos.', null=True)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('DNF', 'DNF'), ('DNS', 'DNS'), ('DQ', 'DQ')], default='OK', max_length=3)),
                ('judge_name', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heat_results', to='registration.athleteentry')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.workoutheat')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heat_results', to='registration.team')),
            ],
            options={
                'ordering': ('heat_id', 'lane'),
                'unique_together': {('heat', 'lane')},
            },
        ),
    ]
