# Generated by Django 5.0.6 on 2025-08-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_date_of_birth_profile_id_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_document',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Documento de identidad'),
        ),
    ]
