# Generated by Django 5.0.6 on 2025-08-12 15:13

import compcore.apps.registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_athleteentry_unique_together_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='join_code',
            field=models.CharField(default=compcore.apps.registration.models.make_join_code, max_length=12, unique=True),
        ),
    ]
