# Generated by Django 5.0.6 on 2025-08-12 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_division_max_age_division_min_age_and_more'),
        ('registration', '0003_alter_team_join_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athleteentry',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('event', 'division', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='athleteentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='athleteentry',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.division'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.division'),
        ),
        migrations.AlterField(
            model_name='team',
            name='join_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('event', 'division', 'name')},
        ),
    ]
