# Generated by Django 5.0.6 on 2025-08-27 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_division_options_alter_event_options_and_more'),
        ('registration', '0004_alter_athleteentry_options_alter_team_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('division', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='athleteentry',
            unique_together={('user', 'division')},
        ),
        migrations.AlterField(
            model_name='athleteentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='athleteentry',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.division'),
        ),
        migrations.AlterField(
            model_name='athleteentry',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='join_code',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
        migrations.RemoveField(
            model_name='athleteentry',
            name='paid',
        ),
    ]
