# Generated by Django 5.0.6 on 2025-08-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together={('event', 'order')},
        ),
        migrations.AddField(
            model_name='division',
            name='capacity_individuals',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='capacity_teams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FINISHED', 'Finished')], default='OPEN', max_length=16),
        ),
        migrations.AlterField(
            model_name='workout',
            name='scoring_type',
            field=models.CharField(choices=[('TIME', 'Time (menor mejor)'), ('REPS', 'Reps (mayor mejor)'), ('LOAD', 'Load (mayor mejor)'), ('POINTS', 'Points (mayor mejor)')], default='REPS', max_length=12),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('event', 'name')},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='description',
        ),
    ]
