# Generated by Django 5.0.6 on 2025-08-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_workout_options_alter_workout_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='female_quota',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cupo mujeres'),
        ),
        migrations.AddField(
            model_name='division',
            name='male_quota',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cupo hombres'),
        ),
    ]
