# Generated by Django 5.0.6 on 2025-08-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_division_female_quota_division_male_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='female_quota',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='male_quota',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
