# Generated by Django 5.0.6 on 2025-08-14 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_division_max_age_division_min_age_and_more'),
        ('registration', '0004_alter_athleteentry_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='heat_capacity',
            field=models.PositiveIntegerField(default=10, help_text='Atletas o equipos por heat.'),
        ),
        migrations.CreateModel(
            name='WorkoutHeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heat_number', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.division')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.workout')),
            ],
            options={
                'ordering': ('workout', 'division', 'heat_number'),
                'unique_together': {('workout', 'division', 'heat_number')},
            },
        ),
        migrations.CreateModel(
            name='HeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.PositiveIntegerField(blank=True, null=True)),
                ('is_manual', models.BooleanField(default=False, help_text='Marcado manualmente por admin.')),
                ('locked', models.BooleanField(default=False, help_text='No mover en re-seeding automático.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('athlete_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.athleteentry')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.team')),
                ('heat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.workoutheat')),
            ],
            options={
                'ordering': ('heat', 'lane', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='heatassignment',
            constraint=models.UniqueConstraint(fields=('heat', 'athlete_entry'), name='uniq_heat_entry', violation_error_message='Este atleta ya está asignado a este heat.'),
        ),
        migrations.AddConstraint(
            model_name='heatassignment',
            constraint=models.UniqueConstraint(fields=('heat', 'team'), name='uniq_heat_team', violation_error_message='Este equipo ya está asignado a este heat.'),
        ),
    ]
