# Generated by Django 5.0.6 on 2025-08-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_division_heat_capacity_workoutheat_heatassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutheat',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutheat',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
