# Generated by Django 5.0.6 on 2025-08-27 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_workoutheat_is_published_workoutheat_published_at'),
        ('registration', '0004_alter_athleteentry_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('event', 'name')},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_date', 'name')},
        ),
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ('event', 'order')},
        ),
        migrations.RemoveConstraint(
            model_name='heatassignment',
            name='uniq_heat_entry',
        ),
        migrations.RemoveField(
            model_name='division',
            name='capacity_individuals',
        ),
        migrations.RemoveField(
            model_name='division',
            name='capacity_teams',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='cap_time_seconds',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='scoring_type',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='title',
        ),
        migrations.RemoveField(
            model_name='workoutheat',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='workoutheat',
            name='published_at',
        ),
        migrations.AddField(
            model_name='division',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='0 = sin límite'),
        ),
        migrations.AddField(
            model_name='division',
            name='gender',
            field=models.CharField(choices=[('ANY', 'Mixto / Cualquiera'), ('M', 'Masculino'), ('F', 'Femenino'), ('MX', 'Mixto (equipos)')], default='ANY', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='scoring',
            field=models.CharField(choices=[('TIME', 'Time (menor mejor)'), ('REPS', 'Reps (mayor mejor)'), ('LOAD', 'Load (mayor mejor)'), ('POINTS', 'Points (mayor mejor)')], default='TIME', max_length=12),
        ),
        migrations.AddField(
            model_name='workout',
            name='time_cap_seconds',
            field=models.PositiveIntegerField(default=0, help_text='0 = sin cap'),
        ),
        migrations.AddField(
            model_name='workoutheat',
            name='lane_count',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FINISHED', 'Finished')], default='DRAFT', max_length=16),
        ),
        migrations.AlterField(
            model_name='workout',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='heatassignment',
            constraint=models.UniqueConstraint(fields=('heat', 'athlete_entry'), name='uniq_heat_athlete', violation_error_message='Este atleta ya está asignado a este heat.'),
        ),
    ]
