# Generated by Django 5.0.6 on 2025-08-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_division_options_alter_event_options_and_more'),
        ('registration', '0005_alter_team_options_alter_team_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='heatassignment',
            name='uniq_heat_team',
        ),
        migrations.RemoveConstraint(
            model_name='heatassignment',
            name='uniq_heat_athlete',
        ),
        migrations.AddField(
            model_name='event',
            name='allow_self_signup',
            field=models.BooleanField(default=False, help_text="Si está activo, se muestra el enlace de 'Crear cuenta' para atletas."),
        ),
        migrations.AddConstraint(
            model_name='heatassignment',
            constraint=models.UniqueConstraint(fields=('heat', 'athlete_entry'), name='uniq_heat_athlete'),
        ),
        migrations.AddConstraint(
            model_name='heatassignment',
            constraint=models.UniqueConstraint(fields=('heat', 'team'), name='uniq_heat_team'),
        ),
    ]
