# Generated by Django 5.0.6 on 2025-08-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_heatassignment_uniq_heat_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutheat',
            options={'ordering': ('workout', 'heat_number')},
        ),
        migrations.AlterUniqueTogether(
            name='workoutheat',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='workoutheat',
            constraint=models.UniqueConstraint(fields=('workout', 'heat_number'), name='uniq_workout_heatnumber'),
        ),
    ]
