# Generated by Django 5.0.6 on 2025-08-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_align_heatassigment_created_at'),
        ('registration', '0005_alter_team_options_alter_team_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ('name', 'id')},
        ),
        migrations.AlterModelOptions(
            name='heatassignment',
            options={'ordering': ('heat', 'lane')},
        ),
        migrations.RemoveConstraint(
            model_name='heatassignment',
            name='uniq_heat_athlete',
        ),
        migrations.RemoveConstraint(
            model_name='heatassignment',
            name='uniq_heat_team',
        ),
        migrations.RemoveField(
            model_name='division',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='time_cap_seconds',
        ),
        migrations.AlterField(
            model_name='division',
            name='gender',
            field=models.CharField(choices=[('ANY', 'Mixto / Cualquiera'), ('M', 'Masculino'), ('F', 'Femenino')], default='ANY', max_length=8),
        ),
        migrations.AlterField(
            model_name='division',
            name='heat_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Si está vacío, usa lanes_default del evento.', null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='slug',
            field=models.SlugField(help_text='Slug único dentro del evento.'),
        ),
        migrations.AlterField(
            model_name='division',
            name='team_size',
            field=models.PositiveIntegerField(default=1, help_text='1 = Individual'),
        ),
        migrations.AlterField(
            model_name='heatassignment',
            name='locked',
            field=models.BooleanField(default=False, help_text='No mover en re-siembra.'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='order',
            field=models.PositiveIntegerField(help_text='Orden del WOD dentro del evento (1..N).'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='scoring',
            field=models.CharField(choices=[('TIME', 'Time'), ('REPS', 'Reps'), ('WEIGHT', 'Weight'), ('POINTS', 'Points')], default='TIME', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='heatassignment',
            constraint=models.CheckConstraint(check=models.Q(('athlete_entry__isnull', False), ('team__isnull', False), _negated=True), name='only_one_entrant'),
        ),
    ]
