# Generated by Django 5.0.6 on 2025-08-11 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=64)),
                ('tie_break', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='PENDING', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.athleteentry')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.workout')),
            ],
        ),
    ]
